default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dv
  password: password

development:
  <<: *default
  database: story_development

test:
  <<: *default
  database: story_test

production:
  <<: *default
  database: story_production
